### ISSUE TITLE
Where can I get Purple perl module for this plugin?

### ISSUE THREAD

**Issue by MurzNN** [Eckankar/YouTubeTitleAdderPidgin#1]
When I try to run this plugin in Ubuntu with Pidgin installed - I got the error:

> Can't locate Purple.pm in @INC (you may need to install the Purple module) (@INC contains: /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at ./youtube-title.pl line 2.
> BEGIN failed--compilation aborted at ./youtube-title.pl line 2.

But I can't see package with purple modules for Perl in Ubuntu repository. Where can I get this module?

**Comment by MurzNN** [comment]
Seems that Purple.pm file exists in system at /usr/lib/purple-2/perl/Purple.pm but script don't see it :(

**Comment by MurzNN** [comment]
If I manually copy the file to INC folders - I got another error:

> Can't load '/etc/perl/auto/Purple/Purple.so' for module Purple: /etc/perl/auto/Purple/Purple.so: undefined symbol: g_free at /usr/share/perl/5.18/XSLoader.pm line 68.
>  at /etc/perl/Purple.pm line 52.
> Compilation failed in require at ./youtube-title.pl line 2.
> BEGIN failed--compilation aborted at ./youtube-title.pl line 2.

Here is issue about this: https://developer.pidgin.im/ticket/17028
So there are no way to fix this?

**Comment by Eckankar** [comment]
The script isn't intended to be run outside of Pidgin.

Are you trying to access it via the Pidgin plugins menu, or by running it using perl?

You can install it in Pidgin using the following guide: https://developer.pidgin.im/wiki/ThirdPartyPlugins#InstallingPlugins

**Comment by MurzNN** [comment]
I have enable it in Pidgin, but seems it isn't working, so I try to run in via command line for check errors.

**Comment by Eckankar** [comment]
Ah, yes, YouTube changed their API a while back.

I've created #2 to address this issue, so I will close this issue.

You're welcome to give it a try if you wish.

**Comment by MurzNN** [comment]
Thanks for the info! I will try to change the code for new API. But at now I don't understand how I can debug the code for viewing debug output and code errors, for understanding the problems in development process. Before I use command line for debug script code.

**Comment by Eckankar** [comment]
@MurzNN https://developer.pidgin.im/wiki/Scripting%20and%20Plugins has some links on how to develop for Pidgin.

What I think I used to do was make a change, then restart pidgin and check the debug console.
